import {box, children, exact, href, manifest, sourceFor, type Box} from './data';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';

export const siteUrl='https://chicagobudget.com';
export const snapshot='https://github.com/gettty/chicagobudget/tree/main/data/public/2026';
export const rawSnapshot='https://raw.githubusercontent.com/gettty/chicagobudget/main/data/public/2026';
export const exportDate=String(manifest.run_at).slice(0,10);
const publishedManifest=JSON.parse(readFileSync(join(process.cwd(),'../data/public/2026/site/manifest.json'),'utf8')) as {commit:string;run_at:string;totals:Record<string,number>;gross_city_cents:number};
export const snapshotDate=publishedManifest.run_at.slice(0,10);
export const snapshotVersion=publishedManifest.commit;
export const snapshotAmount=(root:string)=>exact(publishedManifest.totals[root]);
export const snapshotGross=exact(publishedManifest.gross_city_cents);
export const scopeNote='These are three separate governments, not one official consolidated City budget. The City and Park District use 2026 budgets, while CPS FY2026 runs July 2025 through June 2026. Transfers across governments may overlap.';
export const dollars=(node:Box)=>exact(node.amount_cents);
export function required(id:string):Box {const node=box(id);if(!node)throw new Error(`Missing budget node ${id}`);return node;}
export function citations(nodes:Box[]){const seen=new Set<string>();return nodes.flatMap(node=>sourceFor(node).filter(source=>typeof source.url==='string'&&/^https:\/\//.test(source.url)).map(source=>({url:String(source.url),label:String(source.name||source.doc||source.dataset||'Official source')}))).filter(source=>{if(seen.has(source.url))return false;seen.add(source.url);return true;});}
export type Guide={slug:string;title:string;answer:string;ids:string[];reading:string;limits:string;related:string[]};
export const guides:Guide[]=[
 {slug:'city-adopted-budget',title:'What is Chicago’s adopted 2026 City budget?',answer:'The City’s adopted net appropriation is the City root below. It is not the sum of all three governments on this site.',ids:['city','city.public-safety','city.infrastructure-services','city.retirement'],reading:'The net City figure excludes a separate cross-fund view. The categories shown here are selected parts of the same City total, not extra budgets to add on top.',limits:'An appropriation authorizes spending; it is not a report of payments made. Negative adjustments and internal accounting matter when reconciling categories.',related:['net-versus-gross','pensions-and-debt','per-resident']},
 {slug:'net-versus-gross',title:'Why do Chicago’s net and gross budgets differ?',answer:'The published City net view removes money counted twice across funds and includes a separate negative OBM adjustment. Neither figure is the combined budget of City, CPS and Parks.',ids:['city','city-twice','city.obm-unexplained'],reading:'The counted-twice root documents internal transactions rather than additional services. The negative OBM adjustment is a separate reconciliation item. Do not add either row as a new government budget.',limits:'Different publications may use different definitions of gross, net and fund transfers. The adjustment is not a spending category whose final recipients are known; inspect its budget box and source before interpreting it.',related:['city-adopted-budget','pensions-and-debt']},
 {slug:'police-budget',title:'What is the Chicago Police Department’s 2026 budget?',answer:'The department total below is an adopted City appropriation, not its actual year-end spending.',ids:['city.public-safety.chicago-police-department','city.public-safety.chicago-police-department.pay-for-workers','city.public-safety.chicago-police-department.overtime','city.public-safety.chicago-police-department.contracts-and-services'],reading:'The rows beneath the department are selected branches of its appropriation. Payroll and overtime are budgeted categories; they should not be equated with employee take-home pay.',limits:'Some grant money has not been assigned to individual projects. Do not treat the department appropriation as all public safety spending or as a payment ledger.',related:['fire-budget','overtime-budget','city-adopted-budget']},
 {slug:'fire-budget',title:'What is the Chicago Fire Department’s 2026 budget?',answer:'The Fire Department figure below is its adopted City appropriation, distinct from the separate Fire pension contribution.',ids:['city.public-safety.chicago-fire-department','city.public-safety.chicago-fire-department.pay-for-workers','city.public-safety.chicago-fire-department.overtime','city.retirement.firemen-s-annuity-and-benefit-fund'],reading:'The pension row comes from a separate City retirement branch and is not a child of the Fire Department total. Do not add these rows as though they were one department subtotal.',limits:'Budgeted overtime is not overtime already paid. The department’s grant and program allocations may not identify eventual recipients.',related:['police-budget','overtime-budget','pensions-and-debt']},
 {slug:'overtime-budget',title:'How much overtime is budgeted for Chicago police and fire?',answer:'The two overtime appropriations below are budget amounts for the departments, not actual overtime checks.',ids:['city.public-safety.chicago-police-department.overtime','city.public-safety.chicago-fire-department.overtime','city.public-safety.office-of-emergency-management-and-communication.overtime'],reading:'The emergency-management line provides context that public-safety overtime is not limited to police and fire. Each line is nested inside its own department.',limits:'Year-to-date payment data covers only its stated partial period and is a different measure from the full-year appropriation. Do not infer future overtime spending by extrapolation.',related:['police-budget','fire-budget','gaps-and-estimates']},
 {slug:'pensions-and-debt',title:'Are pension contributions and debt balances the same thing?',answer:'No. These are annual budget allocations toward retirement funds and loan repayment, not the total pension liability or outstanding debt.',ids:['city.retirement','city.loans','cps.pensions','cps.debt','parks.retirement-pensions','parks.paying-back-loans'],reading:'Each government reports its own retirement or debt category. The CPS fiscal-year figures should not be presented as City calendar-year pension obligations.',limits:'Annual appropriations cannot establish unfunded liabilities or outstanding principal. Debt service can include interest as well as repayment. These rows are not one official consolidated liability statement.',related:['city-adopted-budget','cps-fiscal-year','parks-budget']},
 {slug:'cps-fiscal-year',title:'What is the CPS FY2026 budget and when is its fiscal year?',answer:'Chicago Public Schools’ FY2026 runs July 2025 through June 2026, unlike the City calendar-year budget.',ids:['cps','cps.schools','cps.citywide','cps.pensions','cps.debt','cps.capital'],reading:'Schools, systemwide activities, pensions, debt and capital are separate branches of the CPS budget tree. The root is the approved CPS budget represented by this export.',limits:'Do not add CPS to the City and call the result an official City budget. Fiscal-year boundaries differ, and intergovernmental transfers may appear in more than one place.',related:['school-budgets','city-adopted-budget','pensions-and-debt']},
 {slug:'school-budgets',title:'Where can I find a Chicago public school budget?',answer:'Start in the CPS schools branch, then browse district-run and other school groups to locate a school-level allocation.',ids:['cps.schools','cps.schools.district-run','cps.citywide'],reading:'The schools category is a part of the full CPS FY2026 budget. District-run schools are a narrower branch, not a second total to add to schools.',limits:'A school’s displayed allocation is not every district service benefiting that school. Centrally budgeted expenses and shared operations may sit outside its school box.',related:['cps-fiscal-year','gaps-and-estimates']},
 {slug:'parks-budget',title:'What is in the Chicago Park District’s 2026 budget?',answer:'The Park District root is the printed all-funds operating appropriation. Its published net appropriation excludes internal service earnings.',ids:['parks','parks.parks-and-recreation','parks.maintaining-the-parks','parks.managed-venues','parks.building-and-fixing-parks'],reading:'Managed venues and parks/recreation are different branches. The building-and-fixing category here is within the operating appropriation, not a substitute for a multi-year capital plan.',limits:'The Park District is a separate government. Its all-funds total differs from its net appropriation, and operating appropriations do not capture every future capital project.',related:['city-adopted-budget','per-resident','gaps-and-estimates']},
 {slug:'per-resident',title:'Is a per-resident budget figure my tax bill?',answer:'No. Dividing a public budget by population produces an illustrative average of spending, not what any resident owes.',ids:['city','cps','parks'],reading:'The three root amounts belong to separate governments with different accounting periods. Taxes are only one funding source alongside fees, grants, borrowing and enterprise revenue.',limits:'Residents, workers, visitors and businesses use services and pay different taxes. Cross-government transfers can overlap; these rows are not an official consolidated per-person total.',related:['city-adopted-budget','cps-fiscal-year','parks-budget']},
 {slug:'gaps-and-estimates',title:'Why do budget boxes stop or show estimates?',answer:'A box stops when its published evidence does not support a reliable finer split. An estimate is labeled separately from an adopted appropriation or a payment.',ids:['city','cps','parks'],reading:'Follow each box’s basis, note and citation. Budget, proxy, government estimate and paid-to-date are different kinds of evidence, not interchangeable precision.',limits:'A partial-year payment extract cannot prove full-year spending. Unassigned grants or reserves should not be fabricated into projects, vendors or individuals.',related:['overtime-budget','school-budgets','per-resident']}
];
export const datasetEntries=[{slug:'city',name:'City of Chicago 2026 adopted net budget',root:'city',period:'2026 calendar-year adopted appropriation',temporal:'2026-01-01/2026-12-31',coverage:'Chicago, Illinois',qualification:'Net City appropriation excludes the cross-fund counted-twice view; gross is shown separately.'},{slug:'cps',name:'Chicago Public Schools FY2026 approved budget',root:'cps',period:'FY2026, July 2025 through June 2026',temporal:'2025-07-01/2026-06-30',coverage:'Chicago Public Schools, Illinois',qualification:'School boxes do not contain all centrally budgeted services.'},{slug:'parks',name:'Chicago Park District 2026 operating appropriations',root:'parks',period:'2026 operating budget',temporal:'2026',coverage:'Chicago Park District, Illinois',qualification:'All-funds operating total; net appropriation removes internal service earnings. Not a multi-year capital plan.'}] as const;
export function distribution(path:string,format:string){return {'@type':'DataDownload',encodingFormat:format,contentUrl:`${rawSnapshot}/${path}`,name:path};}
export function datasetSchema(entry:typeof datasetEntries[number]){const node=required(entry.root),source=citations([node]);return {'@context':'https://schema.org','@type':'Dataset',name:entry.name,description:`${entry.period}. ${entry.qualification} Amounts are integer cents. Derived budget tree, not an official consolidated City budget.`,url:`${siteUrl}/datasets/2026/${entry.slug}/`,identifier:`${snapshotVersion}:${entry.root}`,version:snapshotVersion,dateModified:snapshotDate,temporalCoverage:entry.temporal,spatialCoverage:{'@type':'Place',name:entry.coverage},creator:{'@type':'Organization',name:'Chicago Budget',url:siteUrl},publisher:{'@type':'Organization',name:'Chicago Budget',url:siteUrl},isBasedOn:source.map(s=>s.url),distribution:[distribution(`tree/${entry.slug}/_root.json`,'application/json'),distribution('tree/manifest.json','application/json'),distribution('tree/lookup.json','application/json'),distribution('catalog.json','application/json')]};}
export function tableRows(ids:string[]){return ids.map(required).map(node=>({node,amount:dollars(node),url:href(node)}));}
export function guideSources(ids:string[]){return citations(ids.map(required));}
export function childrenRows(id:string){return children(id).slice(0,12).map(node=>({node,amount:dollars(node),url:href(node)}));}
